# Generated by Django 5.1.6 on 2025-02-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='text',
            new_name='title',
        ),
    ]
